/**
 * learned-blocking.ts — Data-driven predicate selection for blocking.
 * Edge-safe: no `node:` imports.
 *
 * Ports goldenmatch/core/learned_blocking.py. Given a labelled set of
 * matching pairs, greedy-select predicates (equal, soundex, prefix,
 * qgram) that maximize recall while minimizing candidate pair count.
 */

import type { Row, BlockResult, ScoredPair } from "./types.js";
import { applyTransform, soundex } from "./transforms.js";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface LearnedPredicate {
  readonly type: "equal" | "soundex" | "first_n_chars" | "qgram";
  readonly field: string;
  readonly n?: number;
  readonly recall: number;
  readonly reduction: number;
}

export interface LearnedRules {
  readonly predicates: readonly LearnedPredicate[];
  readonly minRecall: number;
  readonly minReduction: number;
  readonly learnedAt: string;
}

export interface LearnBlockingOptions {
  readonly minRecall?: number;
  readonly minReduction?: number;
  readonly predicateDepth?: number;
}

// ---------------------------------------------------------------------------
// Predicate evaluation
// ---------------------------------------------------------------------------

function fieldValue(row: Row, field: string): string | null {
  const v = row[field];
  if (v === null || v === undefined) return null;
  const s = typeof v === "string" ? v : String(v);
  const trimmed = s.trim();
  return trimmed.length === 0 ? null : trimmed;
}

type PredicateFn = (row: Row) => string | null;

function buildPredicateFn(
  pred: Omit<LearnedPredicate, "recall" | "reduction">,
): PredicateFn {
  const { type, field, n } = pred;
  switch (type) {
    case "equal":
      return (row) => {
        const v = fieldValue(row, field);
        return v === null ? null : applyTransform(v, "lowercase");
      };
    case "soundex":
      return (row) => {
        const v = fieldValue(row, field);
        if (v === null) return null;
        const code = soundex(v);
        return code === "0000" ? null : code;
      };
    case "first_n_chars": {
      const len = n ?? 3;
      return (row) => {
        const v = fieldValue(row, field);
        if (v === null) return null;
        const lc = v.toLowerCase();
        return lc.length >= len ? lc.slice(0, len) : null;
      };
    }
    case "qgram": {
      const size = n ?? 3;
      return (row) => {
        const v = fieldValue(row, field);
        if (v === null) return null;
        const lc = v.toLowerCase();
        if (lc.length < size) return null;
        // Use the first q-gram as the block key (simple, deterministic).
        return lc.slice(0, size);
      };
    }
  }
}

interface PredicateStats {
  readonly capturedPairKeys: Set<string>;
  readonly candidatePairs: number;
  readonly recall: number;
  readonly reduction: number;
  readonly blocks: Map<string, number[]>;
}

function pairKey(a: number, b: number): string {
  return a < b ? `${a}|${b}` : `${b}|${a}`;
}

function evaluatePredicate(
  rows: readonly Row[],
  knownPairs: readonly ScoredPair[],
  fn: PredicateFn,
  totalPossiblePairs: number,
): PredicateStats {
  // Group rows by their block key.
  const blocks = new Map<string, number[]>();
  for (let i = 0; i < rows.length; i++) {
    const row = rows[i]!;
    const key = fn(row);
    if (key === null) continue;
    const list = blocks.get(key);
    if (list) list.push(i);
    else blocks.set(key, [i]);
  }

  // Count candidate pairs generated by this predicate.
  let candidatePairs = 0;
  for (const ids of blocks.values()) {
    const n = ids.length;
    candidatePairs += (n * (n - 1)) / 2;
  }

  // Compute which known pairs are captured: both row indices share a block.
  // Build row->block-key-set index.
  const idToKeys = new Map<number, Set<string>>();
  for (const [key, ids] of blocks) {
    for (const id of ids) {
      let set = idToKeys.get(id);
      if (!set) {
        set = new Set<string>();
        idToKeys.set(id, set);
      }
      set.add(key);
    }
  }

  const capturedPairKeys = new Set<string>();
  for (const pair of knownPairs) {
    const keysA = idToKeys.get(pair.idA);
    const keysB = idToKeys.get(pair.idB);
    if (!keysA || !keysB) continue;
    for (const k of keysA) {
      if (keysB.has(k)) {
        capturedPairKeys.add(pairKey(pair.idA, pair.idB));
        break;
      }
    }
  }

  const recall =
    knownPairs.length === 0 ? 0 : capturedPairKeys.size / knownPairs.length;
  const reduction =
    totalPossiblePairs === 0
      ? 1
      : Math.max(0, 1 - candidatePairs / totalPossiblePairs);

  return { capturedPairKeys, candidatePairs, recall, reduction, blocks };
}

// ---------------------------------------------------------------------------
// Greedy predicate selection
// ---------------------------------------------------------------------------

/**
 * Learn blocking rules from known-matching pairs.
 *
 * Evaluates candidate predicates for each column, then greedily selects
 * predicates that add the most new recall per candidate pair introduced,
 * stopping when minRecall is reached (or when options.predicateDepth is
 * exceeded).
 */
export function learnBlockingRules(
  rows: readonly Row[],
  knownPairs: readonly ScoredPair[],
  columns: readonly string[],
  options?: LearnBlockingOptions,
): LearnedRules {
  const minRecall = options?.minRecall ?? 0.95;
  const minReduction = options?.minReduction ?? 0.9;
  const predicateDepth = options?.predicateDepth ?? 3;

  const totalPossible = (rows.length * (rows.length - 1)) / 2;

  const candidates: { pred: LearnedPredicate; stats: PredicateStats }[] = [];
  for (const field of columns) {
    const predVariants: {
      type: LearnedPredicate["type"];
      n?: number;
    }[] = [
      { type: "equal" },
      { type: "soundex" },
      { type: "first_n_chars", n: 3 },
      { type: "first_n_chars", n: 4 },
      { type: "qgram", n: 3 },
    ];
    for (const variant of predVariants) {
      const predPartial: Omit<LearnedPredicate, "recall" | "reduction"> =
        variant.n !== undefined
          ? { type: variant.type, field, n: variant.n }
          : { type: variant.type, field };
      const fn = buildPredicateFn(predPartial);
      const stats = evaluatePredicate(rows, knownPairs, fn, totalPossible);
      if (stats.recall === 0) continue;
      // Reject predicates whose reduction falls below threshold unless
      // they contribute unique recall (caught in the greedy loop below).
      const pred: LearnedPredicate = {
        ...predPartial,
        recall: stats.recall,
        reduction: stats.reduction,
      };
      candidates.push({ pred, stats });
    }
  }

  // Greedy selection: at each step pick the predicate that contributes the
  // most new captured pairs per candidate pair introduced.
  const selected: LearnedPredicate[] = [];
  const covered = new Set<string>();

  while (selected.length < predicateDepth) {
    let best: { pred: LearnedPredicate; gain: number; stats: PredicateStats } | null = null;

    for (const cand of candidates) {
      if (selected.includes(cand.pred)) continue;

      let newCaptures = 0;
      for (const pk of cand.stats.capturedPairKeys) {
        if (!covered.has(pk)) newCaptures++;
      }
      if (newCaptures === 0) continue;
      if (cand.stats.reduction < minReduction && newCaptures === 0) continue;

      // Marginal efficiency: new captures per candidate pair (lower cost
      // predicates favored). Avoid divide-by-zero.
      const cost = Math.max(1, cand.stats.candidatePairs);
      const gain = newCaptures / cost;

      if (best === null || gain > best.gain) {
        best = { pred: cand.pred, gain, stats: cand.stats };
      }
    }

    if (best === null) break;
    selected.push(best.pred);
    for (const pk of best.stats.capturedPairKeys) covered.add(pk);

    const achievedRecall =
      knownPairs.length === 0 ? 0 : covered.size / knownPairs.length;
    if (achievedRecall >= minRecall) break;
  }

  return {
    predicates: selected,
    minRecall,
    minReduction,
    learnedAt: new Date().toISOString(),
  };
}

// ---------------------------------------------------------------------------
// Apply learned rules to produce blocks
// ---------------------------------------------------------------------------

/**
 * Apply learned rules to rows, returning one BlockResult per non-empty,
 * non-oversized block. Each predicate is its own pass (OR'd together).
 */
export function applyLearnedBlocks(
  rows: readonly Row[],
  rules: LearnedRules,
  maxBlockSize: number,
): BlockResult[] {
  const out: BlockResult[] = [];

  for (let p = 0; p < rules.predicates.length; p++) {
    const pred = rules.predicates[p]!;
    const fn = buildPredicateFn(pred);
    const blocks = new Map<string, Row[]>();
    for (const row of rows) {
      const key = fn(row);
      if (key === null) continue;
      const list = blocks.get(key);
      if (list) list.push(row);
      else blocks.set(key, [row]);
    }

    for (const [key, blockRows] of blocks) {
      if (blockRows.length < 2) continue;
      if (blockRows.length > maxBlockSize) continue;
      out.push({
        blockKey: `learned:${pred.type}:${pred.field}=${key}`,
        rows: blockRows,
        strategy: "learned",
        depth: p,
      });
    }
  }

  return out;
}
